# Generated by Django 4.1 on 2022-09-09 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='last_name_name',
            new_name='last_name',
        ),
    ]
